name: Generate tweak packages

on:
  workflow_dispatch:
    inputs:
      enable_youpip:
        { description: "Generate YouPiP", type: boolean, default: false }
      enable_ytuhd:
        { description: "Generate YTUHD", type: boolean, default: false }
      enable_yq:
        { description: "Generate YouQuality", type: boolean, default: false }
      enable_ryd:
        {
          description: "Generate Return YouTube Dislikes",
          type: boolean,
          default: false,
        }
      enable_ytabc:
        { description: "Generate YTABConfig", type: boolean, default: false }
      enable_demc:
        {
          description: "Generate DontEatMyContent",
          type: boolean,
          default: false,
        }
      enable_ytweaks:
        { description: "Generate YTweaks", type: boolean, default: false }
      enable_gonerino:
        { description: "Generate Gonerino", type: boolean, default: false }
      enable_youspeed:
        { description: "Generate YouSpeed", type: boolean, default: false }
      enable_ytlcm:
        {
          description: "Generate YTLowContrastMode",
          type: boolean,
          default: false,
        }
      enable_VolumeBoostYT:
        { description: "Generate VolumeBoostYT", type: boolean, default: false }
      enable_YouGetCaption:
        { description: "Generate YouGetCaption", type: boolean, default: false }
      enable_ytpf:
        { description: "Generate YTPlaybackFix", type: boolean, default: false }
      enable_ytpfBETA:
        {
          description: "Generate the latest YTPlaybackFix beta",
          type: boolean,
          default: false,
        }
      enable_ycq:
        {
          description: "Generate YouChooseQuality",
          type: boolean,
          default: false,
        }
      enable_ys:
        { description: "Generate YouShare", type: boolean, default: false }
      enable_youloop:
        { description: "Generate YouLoop", type: boolean, default: false }
      enable_youmute:
        { description: "Generate YouMute", type: boolean, default: false }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-tweaks:
    uses: ./.github/workflows/_build_tweaks.yml
    with:
      enable_youpip: ${{ inputs.enable_youpip }}
      enable_ytuhd: ${{ inputs.enable_ytuhd }}
      enable_yq: ${{ inputs.enable_yq }}
      enable_ryd: ${{ inputs.enable_ryd }}
      enable_ytabc: ${{ inputs.enable_ytabc }}
      enable_demc: ${{ inputs.enable_demc }}
      enable_ytweaks: ${{ inputs.enable_ytweaks }}
      enable_gonerino: ${{ inputs.enable_gonerino }}
      enable_youspeed: ${{ inputs.enable_youspeed }}
      enable_ytlcm: ${{ inputs.enable_ytlcm }}
      enable_VolumeBoostYT: ${{ inputs.enable_VolumeBoostYT }}
      enable_YouGetCaption: ${{ inputs.enable_YouGetCaption }}
      enable_ytpf: ${{ inputs.enable_ytpf }}
      enable_ytpfBETA: ${{ inputs.enable_ytpfBETA }}
      enable_ycq: ${{ inputs.enable_ycq }}
      enable_ys: ${{ inputs.enable_ys }}
      enable_youloop: ${{ inputs.enable_youloop }}
      enable_youmute: ${{ inputs.enable_youmute }}
